### ISSUE TITLE
Misc TODO

### ISSUE THREAD

**Issue by dexterklui** [dexterklui/doraemon-canvas#10]
- [x] refactor: use `defer` attributes instead for `<script>`
- [ ] test: make a list of tests
- [x] perf: reduce cursor lag #19 #20 
- [ ] fix: polygon sides not updated with init
- [ ] feat: bell appearance and animation
- [ ] refactor: css use something like `last-of-class` to select the `ItemSelect` button
- [ ] fix: for `AddImage`, `<input>` add `accept` attribute to limit filetypes
- [ ] feat: resize selection
- [ ] perf: redraw regions technique (clear only prev regions)
- [ ] fix: canvas only resizes up, not resizes down
- [ ] feat: clip the canvas (with canvas clip but not merely in CSS appearance)
- [ ] feat: output the image with doraemon
- [ ] feat: able to clear rather than drawing with drawing tools
